const INDENT = "\t";

function quote(value) {
  // SourceMod signatures conventionally contain literal \xNN sequences. Keep
  // their backslashes intact; only protect the delimiter used by KeyValues.
  return `"${String(value).replaceAll('"', '\\"')}"`;
}

function pushPlatformValues(lines, values, depth) {
  for (const platform of ["windows", "windows64", "linux", "linux64", "mac"]) {
    const value = values?.[platform];
    if (value !== undefined && value !== null && value !== "") {
      lines.push(`${INDENT.repeat(depth)}${quote(platform)}${INDENT}${quote(value)}`);
    }
  }
}

function pushObject(lines, object, depth) {
  for (const [key, value] of Object.entries(object || {})) {
    if (value === undefined || value === null) continue;
    if (typeof value === "object" && !Array.isArray(value)) {
      lines.push(`${INDENT.repeat(depth)}${quote(key)}`, `${INDENT.repeat(depth)}{`);
      pushObject(lines, value, depth + 1);
      lines.push(`${INDENT.repeat(depth)}}`);
    } else if (!Array.isArray(value)) {
      lines.push(`${INDENT.repeat(depth)}${quote(key)}${INDENT}${quote(value)}`);
    }
  }
}

/**
 * Convert normalized SigShop entries into SourceMod's KeyValues gamedata format.
 * The cart may contain entries from more than one game; SourceMod selects the
 * matching game section when the file is loaded.
 */
export function generateGameData(cartEntries, generatedAt = new Date()) {
  const grouped = new Map();

  for (const item of cartEntries) {
    if (!grouped.has(item.game.id)) grouped.set(item.game.id, []);
    grouped.get(item.game.id).push(item);
  }

  const lines = [
    `// Generated by SigShop on ${generatedAt.toISOString()}`,
    "// Review community-provided values before using them on a production server.",
    '"Games"',
    "{",
  ];

  for (const [gameId, items] of grouped) {
    lines.push(`${INDENT}${quote(gameId)}`, `${INDENT}{`);

    const signatures = new Map(items.filter(({ entry }) => entry.signature).map((item) => [item.entry.signature.key || item.entry.gamedataKey || item.entry.name, item]));
    if (signatures.size) {
      lines.push(`${INDENT.repeat(2)}"Signatures"`, `${INDENT.repeat(2)}{`);
      for (const [signatureKey, { entry }] of signatures) {
        lines.push(`${INDENT.repeat(3)}${quote(signatureKey)}`, `${INDENT.repeat(3)}{`);
        lines.push(`${INDENT.repeat(4)}"library"${INDENT}${quote(entry.signature.library)}`);
        pushPlatformValues(lines, entry.signature.values, 4);
        lines.push(`${INDENT.repeat(3)}}`);
      }
      lines.push(`${INDENT.repeat(2)}}`);
    }

    const offsets = new Map(items.filter(({ entry }) => entry.offset).map((item) => [item.entry.offset.key || item.entry.gamedataKey || item.entry.name, item]));
    if (offsets.size) {
      lines.push(`${INDENT.repeat(2)}"Offsets"`, `${INDENT.repeat(2)}{`);
      for (const [offsetKey, { entry }] of offsets) {
        lines.push(`${INDENT.repeat(3)}${quote(offsetKey)}`, `${INDENT.repeat(3)}{`);
        pushPlatformValues(lines, entry.offset.values, 4);
        lines.push(`${INDENT.repeat(3)}}`);
      }
      lines.push(`${INDENT.repeat(2)}}`);
    }

    const functions = items.filter(({ entry }) => entry.functionConfig);
    if (functions.length) {
      lines.push(`${INDENT.repeat(2)}"Functions"`, `${INDENT.repeat(2)}{`);
      for (const { entry } of functions) {
        lines.push(`${INDENT.repeat(3)}${quote(entry.gamedataKey || entry.name)}`, `${INDENT.repeat(3)}{`);
        pushObject(lines, entry.functionConfig, 4);
        lines.push(`${INDENT.repeat(3)}}`);
      }
      lines.push(`${INDENT.repeat(2)}}`);
    }

    lines.push(`${INDENT}}`);
  }

  lines.push("}", "");
  return lines.join("\n");
}

export function downloadTextFile(filename, contents) {
  const blob = new Blob([contents], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
